import React from "react";
import * as Icon from "react-feather";

const navigationConfig = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "collapse",
    icon: <Icon.Home size={20} />,
    children: [
      {
        id: "analyticsDash",
        title: "Analytics",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/",
      },
    ],
  },

  {
    type: "groupHeader",
    groupTitle: "Seller Dashboard",
  },
  // {
  //   id: "editProfile",
  //   title: "Profile",
  //   type: "item",
  //   icon: <Icon.User size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/profile/editProfile",
  //   collapsed: true,
  // },
  {
    id: "student",
    title: "Student",
    type: "collapse",
    icon: <Icon.User size={20} />,
    children: [
      {
        id: "studentList",
        title: "Student List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/student/studentList",
        // collapsed: true,
      },
      {
        id: "enrollList",
        title: "Student Enroll",
        type: "item",
        icon: <Icon.Youtube size={20} />,
        permissions: ["admin", "editor"],
        navLink: "/app/enrollment/enrollList",
      },
      {
        id: "kycList",
        title: "KYC",
        type: "item",
        icon: <Icon.Youtube size={20} />,
        permissions: ["admin", "editor"],
        navLink: "/app/kyc/kycList",
      },
    ],
  },
  {
    id: "teacher",
    title: "Teacher",
    type: "collapse",
    icon: <Icon.UserCheck size={20} />,
    children: [
      {
        id: "addTeacher",
        title: "Add Teacher",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/teacher/addTeacher",
        // collapsed: true,
      },
      {
        id: "teacherList",
        title: "Teacher List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/teacher/teacherList",
        // collapsed: true,
      },
      {
        id: "approvedTeacher",
        title: "Approved Teacher",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/teacher/approvedTeacher",
        // collapsed: true,
      },
    ],
  },
  {
    id: "course",
    title: "Course",
    type: "collapse",
    icon: <Icon.Book size={20} />,
    children: [
      {
        id: "addCourse",
        title: "Add Course",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/course/addCourse",
        // collapsed: true,
      },
      {
        id: "courseList",
        title: "Course List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/course/courseList",
        // collapsed: true,
      },
    ],
  },
  {
    id: "courseCategory",
    title: "Category",
    type: "collapse",
    icon: <Icon.ShoppingBag size={20} />,
    children: [
      {
        id: "categoryList",
        title: "Category List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/category/categoryList",
      },
      // {
      //   id: "subCategory",
      //   title: "Sub-Category",
      //   type: "item",
      //   icon: <Icon.Circle size={12} />,
      //   permissions: ["admin", "editor"],
      //   navLink: "/app/category/subCategory",
      // },
    ],
  },
  {
    id: "affilateProgram",
    title: "Affilate Program",
    type: "collapse",
    icon: <Icon.ShoppingBag size={20} />,
    children: [
      {
        id: "firstPhase",
        title: "First Phase",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/affilateProgram/FirstPhase",
      },

      {
        id: "secondPhase",
        title: "Second Phase",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/affilateProgram/SecondPhase",
      },
    ],
  },
  {
    id: "subscription",
    title: "Subscription",
    type: "collapse",
    icon: <Icon.ShoppingBag size={20} />,
    children: [
      {
        id: "subscriptionList",
        title: "Subscription List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/subscription/subscriptionList",
      },
    ],
  },
  {
    id: "transactionList",
    title: "Transaction",
    type: "item",
    icon: <Icon.Youtube size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/transationHistory/transactionList",
  },
  {
    id: "walletRequest",
    title: "Wallet Request",
    type: "item",
    icon: <Icon.Youtube size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/walletRequest/walletRequest",
  },
  {
    id: "walletList",
    title: "Wallet",
    type: "item",
    icon: <Icon.Youtube size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/wallet/walletList",
  },

  {
    id: "withdrowlist",
    title: "Withdrow List",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/WithDrowList/WithdrowList",
  },

  {
    id: "referralCodeList",
    title: "Referral Code List",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/referralCode/ReferralCodeList",
  },

  {
    id: "notification",
    title: " Student Notification",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/notifications/notification",
  },
  {
    id: "notiteachList",
    title: " Teacher Notification",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/notiteach/notiteachList",
  },
  {
    id: "badgeList",
    title: "Badge",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/badge/badgeList",
  },
  {
    id: "levelList",
    title: "Level",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/level/levelList",
  },

  // {
  //   id: "addSubscription",
  //   title: "Subscriptions",
  //   type: "item",
  //   icon: <Icon.Youtube size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/subscription/addSubscription",
  // },

  // {
  //   id: "orderManagement",
  //   title: "Orders Management",
  //   type: "collapse",
  //   icon: <Icon.Truck size={20} />,
  //   children: [
  //     {
  //       id: "order",
  //       title: "All Order",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/order/allOrder",
  //     },
  //     {
  //       id: "pendingOrder",
  //       title: "Pending Order",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/order/pendingOrder",
  //     },
  //     {
  //       id: "cancelledOrder",
  //       title: "Cancelled Order",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/order/cancelledOrder",
  //     },
  //     {
  //       id: "returnedOrder",
  //       title: "Returned Order",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/order/returnedOrder",
  //     },
  //   ],
  // },
  // //     {
  // //       id: "productCategory",
  // //       title: "Category",
  // //       type: "collapse",
  // //       icon: <Icon.ShoppingBag size={20} />,
  // //       children: [
  // //         {
  // //           id: "categoryList",
  // //           title: "Category List",
  // //           type: "item",
  // //           icon: <Icon.Circle size={12} />,
  // //           permissions: ["admin", "editor"],
  // //           navLink: "/app/category/categoryList",
  // //         },
  // //         {
  // //           id: "subCategory",
  // //           title: "Sub-Category",
  // //           type: "item",
  // //           icon: <Icon.Circle size={12} />,
  // //           permissions: ["admin", "editor"],
  // //           navLink: "/app/category/subCategory",
  // //         },
  // //       ],
  // //     },
  // {
  //   id: "purchase",
  //   title: "Purchase",
  //   type: "collapse",
  //   icon: <Icon.TrendingUp size={20} />,
  //   children: [
  //     {
  //       id: "newPruchaseOrder",
  //       title: "New Purchase Order",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/purchase/newPurchaseOrder",
  //     },
  //     {
  //       id: "purchaseOrderList",
  //       title: "Purchase Order List",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/purchase/purchaseOrderList",
  //     },

  //     // {
  //     //   id: "purchaseInvoice",
  //     //   title: "Purchase Invoice",
  //     //   type: "item",
  //     //   icon: <Icon.Circle size={12} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/purchase/purchaseInvoice",
  //     // },
  //     {
  //       id: "purchaseInvoice",
  //       title: "Purchase Invoice",
  //       type: "collapse",
  //       icon: <Icon.Flag size={20} />,
  //       children: [
  //         {
  //           id: "purchaseInvoiceList",
  //           title: "Purchase Invoice List",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/purchase/purchaseInvoice/purchaseInvoiceList",
  //         },
  //       ],
  //     },
  //     // {
  //     //   id: "invoiceSetting",
  //     //   title: "Invoice Setting ",
  //     //   type: "item",
  //     //   icon: <Icon.Circle size={12} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/purchase/invoiceSetting",
  //     // },
  //     // {
  //     //   id: "invoiceDesign",
  //     //     title: "Invoice Design ",
  //     //     type: "item",
  //     //     icon: <Icon.Circle size={12} />,
  //     //     permissions: ["admin", "editor"],
  //     //     navLink: "/app/purchase/invoiceDesign",
  //     //   },
  //   ],
  // },
  // {
  //   id: "reports",
  //   title: "Reports",
  //   type: "collapse",
  //   icon: <Icon.Flag size={20} />,
  //   children: [
  //     {
  //       id: "sales",
  //       title: "By Sales",
  //       type: "collapse",
  //       icon: <Icon.ArrowRight size={20} />,
  //       children: [
  //         {
  //           id: "salesByItem",
  //           title: "Sales By Item",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/reports/bysales/salesByItem",
  //         },
  //         {
  //           id: "salesByCustomer",
  //           title: "Sales By Customer",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/reports/bysales/salesByCustomer",
  //         },
  //         {
  //           id: "invoicedIncome",
  //           title: "Invoiced Income",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/reports/bysales/invoicedIncome",
  //         },
  //       ],
  //     },
  //     {
  //       id: "byactivity",
  //       title: " By Activity",
  //       type: "collapse",
  //       icon: <Icon.ArrowRight size={20} />,
  //       children: [
  //         {
  //           id: "systemMails",
  //           title: "System Mails",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/reports/byactivity/systemMails",
  //         },
  //       ],
  //     },
  //     {
  //       id: "bypaymentsreceived",
  //       title: "By Payments Received",
  //       type: "collapse",
  //       icon: <Icon.ArrowRight size={20} />,
  //       children: [
  //         {
  //           id: "paymentsReceived",
  //           title: "By Payments Received",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/reports/bypaymentsreceived/paymentsReceived",
  //         },
  //       ],
  //     },
  //     {
  //       id: "bypurchases&epenses",
  //       title: "By Purchases & Epenses",
  //       type: "collapse",
  //       icon: <Icon.ArrowRight size={20} />,
  //       children: [
  //         {
  //           id: "purchaseHistoryReportByItem",
  //           title: "Purchases History Report By Item",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink:
  //             "/app/reports/bypurchases&epenses/purchaseHistoryReportByItem",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // // {
  // //   id: "mostViewProductReport",
  // //   title: "Most View Products Report",
  // //   type: "item",
  // //   icon: <Icon.Circle size={12} />,
  // //   permissions: ["admin", "editor"],
  // //   navLink: "/app/report/MostViewProductReport",
  // //     // },
  // //   ],
  // // },
  // {
  //   id: "notificationList",
  //   title: "Notifications",
  //   type: "item",
  //   icon: <Icon.Circle size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/notification/notificationList",
  // },

  // {
  //   id: "setting",
  //   title: "Setting",
  //   type: "collapse",
  //   icon: <Icon.Settings size={20} />,
  //   children: [
  //     {
  //       id: "brandList",
  //       title: "Brand",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/products/brand/brandList",
  //     },
  //     {
  //       id: "taxList",
  //       title: "GST Tax",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/tax/taxList",
  //     },
  //     {
  //       id: "unitList",
  //       title: "Unit",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/products/unit/unitList",
  //     },
  //     {
  //       id: "reasonList",
  //       title: "Reason",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/reason/reasonList",
  //     },
  //     {
  //       id: "transferTypeList",
  //       title: "Transfer Type",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/transferType/transferTypeList",
  //     },
  //     {
  //       id: "productCategory",
  //       title: "Category",
  //       type: "collapse",
  //       icon: <Icon.ShoppingBag size={20} />,
  //       children: [
  //         {
  //           id: "categoryList",
  //           title: "Category List",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/category/categoryList",
  //         },
  //         {
  //           id: "subCategory",
  //           title: "Sub-Category",
  //           type: "item",
  //           icon: <Icon.Circle size={12} />,
  //           permissions: ["admin", "editor"],
  //           navLink: "/app/category/subCategory",
  //         },
  //       ],
  //     },
  //     {
  //       id: "material",
  //       title: "MaterialList",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/material/materialList",
  //     },
  //     {
  //       id: "warehouseList",
  //       title: "Warehouse",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/warehouse/warehouseList",
  //     },
  //   ],
  // },
  // {
  //   id: "varientList  ",
  //   title: "Variant",
  //   type: "item",
  //   icon: <Icon.Circle size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/products/varient/varientList",
  // },
  // {
  //   id: "coupon",
  //   title: "Coupon",
  //   type: "item",
  //   icon: <Icon.Circle size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/products/coupon/coupon",
  // },

  // {
  //   id: "invoice",
  //   title: "Invoice Setting",
  //   type: "item",
  //   icon: <Icon.Settings size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/pages/invoice/invoice",
  //   collapsed: true,
  // },

  // {
  //   id: "shipping",
  //   title: "Shipping Information",
  //   type: "item",
  //   icon: <Icon.Info size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/shipping/shipinfo",

  //   // navLink: "/pages/shipping",
  //   collapsed: true,
  // },

  // {
  //   id: "sales",
  //   title: "Sales",
  //   type: "collapse",
  //   icon: <Icon.TrendingUp size={20} />,
  //   children: [
  //     {
  //       id: "salesByCustomer",
  //       title: "By Customer",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/sales/SalesByCustomer",
  //     },
  //     {
  //       id: "salesByItem",
  //       title: "By Item",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/sales/SalesByItem",
  //     },
  //     {
  //       id: "salesReturnHistory",
  //       title: "Return History",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/sales/SalesReturnHistory",
  //     },
  //     {
  //       id: "invoicedIncome",
  //       title: "invoiced Income",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/sales/InvoicedIncome",
  //     },
  //   ],
  // },

  // {
  //   id: "accountManagement",
  //   title: "Account Management",
  //   type: "collapse",
  //   icon: <Icon.Aperture size={20} />,
  //   children: [
  //     {
  //       id: "payouts",
  //       title: "Payouts",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/accountManagement/payouts",
  //     },

  //     {
  //       id: "commission",
  //       title: "Commission",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/accountManagement/commission",
  //     },
  //   ],
  // },
];

//   {
//     type: "groupHeader",
//     groupTitle: "My Components",
//   },
//   {
//     id: "users",
//     title: "Users",
//     type: "collapse",
//     icon: <Icon.Users size={20} />,
//     children: [
//       {
//         id: "allUsers",
//         title: "All Users",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/users/user/allUsers",
//       },
//     ],
//   },

//       // {
//       //   id: "roleList",
//       //   title: "Roles and Permission",
//       //   type: "item",
//       //   icon: <Icon.Circle size={12} />,
//       //   permissions: ["admin", "editor"],
//       //   navLink: "/app/users/roleAndPermission/roleList",
//       // },

//   {
//     id: "seller",
//     title: "Seller",
//     type: "collapse",
//     icon: <Icon.User size={20} />,
//     children: [
//       {
//         id: "SellerList",
//         title: "All Seller",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/seller/sellerList",
//       },
//     ],
//   },

//   {
//     id: "roleList",
//     title: "Roles and Permission",
//     type: "item",
//     icon: <Icon.GitMerge size={20} />,
//     permissions: ["admin", "editor"],
//     navLink: "/app/roleAndPermission/roleList",
//   },
//   {
//     id: "store",
//     title: "Stock",
//     type: "collapse",
//     icon: <Icon.Database size={20} />,
//     children: [
//       {
//         id: "stores",
//         title: "Stores",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/store/stores/storesList",
//       },
//       {
//         id: "storesRequest",
//         title: "Stores Request",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/store/storesRequest/storesRequestList",
//       },
//     ],
//   },

// {
//   id: "order",
//   title: "Orders & Invoices",
//   type: "collapse",
//   icon: <Icon.ShoppingCart size={20} />,
//   children: [
//     {
//       id: "allOrder",
//       title: "All Order",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/order/allOrder",
//     },
//     {
//       id: "pendingOrder",
//       title: "Pending Order",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/order/pendingOrder",
//     },
//     {
//       id: "orderDelivered",
//       title: "Order Delivered List",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/order/orderDelivered",
//     },
//     {
//       id: "cancelledOrder",
//       title: "Cancelled Order",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/order/cancelledOrder",
//     },
//     {
//       id: "returnedOrder",
//       title: "Returned Order",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/order/returnedOrder",
//     },
//     {
//       id: "invoiceSetting",
//       title: "Invoice Setting ",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/order/invoiceSetting",
//     },
//     {
//       id: "invoiceDesign",
//         title: "Invoice Design ",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/order/invoiceDesign",
//       },
//     ],
//   },

//   {
//     id: "marketing",
//     title: "Marketing Tools",
//     type: "collapse",
//     icon: <Icon.BarChart size={20} />,
//     children: [
//       {
//         id: "advertiesement",
//         title: "advertiesement",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/marketing/advertiesement/advertiesementList",
//       },
//       {
//         id: "pushnotification",
//         title: "Push Notification",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/marketing/pushnotification/addPushnotification",
//       },

//     ]
//   },

//     {
//     id: "sliderList",
//     title: "Slider",
//     icon: <Icon.Sliders size={20} />,
//     type: "item",
//     permissions: ["admin", "editor"],
//     navLink: "/app/slider/sliderList",
//   },
//   {
//     id: "siteSetting",
//     title: "Site Setting",
//     type: "collapse",
//     icon: <Icon.Grid size={20} />,
//     children: [
//       {
//         id: "general",
//         title: "General",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/siteSetting/General",
//       },
//       {
//         id: "emailSetting",
//         title: "Mail Setting",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/siteSetting/emailSetting",
//       },
//       {
//         id: "smsSetting",
//         title: "SMS Setting",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/siteSetting/smsSetting",
//       },
//     ]
//   },
//   {
//     id: "wallet",
//     title: "Wallet",
//     type: "collapse",
//     icon: <Icon.Pocket size={20} />,
//     children: [
//       {
//         id: "walletList",
//         title: "Wallet",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/wallet/walletList",
//       },
//     ]
//   },

//   {
//     id: "helpAndSupport",
//     title: "Help And Support",
//     type: "collapse",
//     icon: <Icon.HelpCircle size={20} />,
//     children: [
//       {
//         id: "importDemo",
//         title: "Import Demo",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/helpAndSupport/importDemo/ImportDemo",
//       },
//     ],
//   },
//   {
//     id: "bank",
//     title: "Bank",
//     type: "collapse",
//     icon: <Icon.Inbox size={20} />,
//     children: [
//       {
//         id: "bank",
//         title: "bank Details",
//         type: "item",
//         icon: <Icon.Circle size={12} />,
//         permissions: ["admin", "editor"],
//         navLink: "/app/bank/bankList",
//       },
//     ]
//   },
//   {
//     id: "privacyPolicy",
//     title: "Privacy Policy",
//     type: "item",
//     icon: <Icon.Save size={20} />,
//     permissions: ["admin", "editor"],
//     navLink: "/app/privacyPolicy/privacyPolicy",
//   },
//   {
//     id: "churnRate",
//     title: "Churn Rate",
//     type: "item",
//     icon: <Icon.Download size={20} />,
//     navLink: "/app/churnRate/churnRate",
//   },

export default navigationConfig;

// {
//     id: "access-control",
//     title: "Access Control",
//     icon: <Icon.Lock size={20} />,
//     type: "item",
//     permissions: ["admin", "editor"],
//     navLink: "/extensions/access-control",
//   },

// {
//   id: "tables",
//   title: "Tables",
//   type: "collapse",
//   icon: <Icon.Server size={20} />,
//   children: [
//     {
//       id: "tablesReactstrap",
//       title: "Reactstrap Tables",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/tables/reactstrap",
//     },
//     {
//       id: "reactTables",
//       title: "React Tables",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/tables/react-tables",
//     },
//     {
//       id: "aggrid",
//       title: "agGrid Table",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/tables/agGrid",
//     },
//     {
//       id: "dataTable",
//       title: "DataTables",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/tables/data-tables",
//     },
// ],
// },

// {
//   id: "importDemo",
//   title: "Import Demo",
//   type: "item",
//   icon: <Icon.Circle size={12} />,
//   permissions: ["admin", "editor"],
//   navLink: "/app/helpAndSupport/importDemo/ImportDemo",
// },

// {
//   id: "email",
//   title: "Email",
//   type: "item",
//   icon: <Icon.Mail size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/email/:filter",
//   filterBase: "/email/inbox",
// },
// {
//   id: "chat",
//   title: "Chat",
//   type: "item",
//   icon: <Icon.MessageSquare size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/chat",
// },

// {
//   id: "roleAndPermission",
//   title: "Roles and Permission",
//   type: "item",
//   icon: <Icon.Circle size={12} />,
//   permissions: ["admin", "editor"],
//   navLink: "/app/roleAndPermission",
// },
// {
//   id: "totalSales",
//   title: "Total Sales",
//   type: "item",
//   icon: <Icon.Circle size={12} />,
//   permissions: ["admin", "editor"],
//   navLink: "/app/report/totalSales/TotalSales",
// },
// {
//   id: "vendorSettlementReport",
//   title: "Sales By Vendor Report",
//   type: "item",
//   icon: <Icon.Circle size={12} />,
//   permissions: ["admin", "editor"],
//   navLink: "/app/report/vendorSettlementReport/SettlementReport",
// },

// {
//     id: "notification",
//     title: "Notifications",
//     type: "item",
//     icon: <Icon.Circle size={12} />,
//     permissions: ["admin", "editor"],
//     navLink: "/app/notification/Notification",
//   },
// {
//   id: "user",
//   title: "User",
//   type: "collapse",
//   icon: <Icon.User size={20} />,
//   children: [
//     {
//       id: "userList",
//       title: "List",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/user/list",
//     },
//     {
//       id: "userView",
//       title: "View",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/user/view",
//     },
//     {
//       id: "userEdit",
//       title: "Edit",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/app/user/edit",
//     },
//   ],
// },

// {
//   id: "todo",
//   title: "Todo",
//   type: "item",
//   icon: <Icon.CheckSquare size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/todo/:filter",
//   filterBase: "/todo/all",
// },
// {
//   id: "calendar",
//   title: "Calendar",
//   type: "item",
//   icon: <Icon.Calendar size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/calendar",

// {
//   type: "groupHeader",
//   groupTitle: "UI ELEMENTS",
// },
// {
//   id: "dataList",
//   title: "Data List",
//   type: "collapse",
//   icon: <Icon.List size={20} />,
//   badge: "primary",
//   badgeText: "new",
//   children: [
//     {
//       id: "listView",
//       title: "List View",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/data-list/list-view",
//     },
//     {
//       id: "thumbView",
//       title: "Thumb View",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/data-list/thumb-view",
//     },
//   ],
// },
// {
//   id: "content",
//   title: "Content",
//   type: "collapse",
//   icon: <Icon.Layout size={20} />,
//   children: [
//     {
//       id: "gird",
//       title: "Grid",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ui-element/grid",
//     },
//     {
//       id: "typography",
//       title: "Typography",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ui-element/typography",
//     },
//     {
//       id: "textUitlities",
//       title: "Text Utilities",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ui-element/textutilities",
//     },
//     {
//       id: "syntaxHighlighter",
//       title: "Syntax Highlighter",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ui-element/syntaxhighlighter",
//     },
//   ],
// },

// {
//   id: "colors",
//   title: "Colors",
//   type: "item",
//   icon: <Icon.Droplet size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/colors/colors",
// },
// {
//   id: "icons",
//   title: "Icons",
//   type: "item",
//   icon: <Icon.Eye size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/icons/reactfeather",
// },
// {
//   id: "cards",
//   title: "Cards",
//   type: "collapse",
//   icon: <Icon.CreditCard size={20} />,
//   children: [
//     {
//       id: "basic",
//       title: "Basic",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/cards/basic",
//     },
//     {
//       id: "statistics",
//       title: "Statistics",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/cards/statistics",
//     },
//     {
//       id: "analytics",
//       title: "Analytics",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/cards/analytics",
//     },
//     {
//       id: "cardActions",
//       title: "Card Actions",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/cards/action",
//     },
//   ],
// },
// {
//   id: "components",
//   title: "Components",
//   type: "collapse",
//   icon: <Icon.Briefcase size={20} />,
//   children: [
//     {
//       id: "alerts",
//       title: "Alerts",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/alerts",
//     },
//     {
//       id: "buttons",
//       title: "Buttons",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/buttons",
//     },
//     {
//       id: "breadCrumbs",
//       title: "Breadcrumbs",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/breadcrumbs",
//     },
//     {
//       id: "carousel",
//       title: "Carousel",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/carousel",
//     },
//     {
//       id: "collapse",
//       title: "Collapse",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/collapse",
//     },
//     {
//       id: "dropDowns",
//       title: "Dropdowns",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/dropdowns",
//     },
//     {
//       id: "listGroup",
//       title: "List Group",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/list-group",
//     },
//     {
//       id: "modals",
//       title: "Modals",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/modals",
//     },
//     {
//       id: "pagination",
//       title: "Pagination",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/pagination",
//     },
//     {
//       id: "navsComponent",
//       title: "Navs Component",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/nav-component",
//     },
//     {
//       id: "navbar",
//       title: "Navbar",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/navbar",
//     },
//     {
//       id: "tabsComponent",
//       title: "Tabs Component",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/tabs-component",
//     },
//     {
//       id: "pillsComponent",
//       title: "Pills Component",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/pills-component",
//     },
//     {
//       id: "tooltips",
//       title: "Tooltips",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/tooltips",
//     },
//     {
//       id: "popovers",
//       title: "Popovers",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/popovers",
//     },
//     {
//       id: "badges",
//       title: "Badges",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/badges",
//     },
//     {
//       id: "pillBadges",
//       title: "Pill Badges",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/pill-badges",
//     },
//     {
//       id: "progress",
//       title: "Progress",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/progress",
//     },
//     {
//       id: "mediaObjects",
//       title: "Media Objects",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/media-objects",
//     },
//     {
//       id: "spinners",
//       title: "Spinners",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/spinners",
//     },
//     {
//       id: "toasts",
//       title: "Toasts",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/components/toasts",
//     },
//   ],
// },
// {
//   id: "extraComponents",
//   title: "Extra Components",
//   type: "collapse",
//   icon: <Icon.Box size={20} />,
//   children: [
//     {
//       id: "autoComplete",
//       title: "Auto Complete",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/extra-components/auto-complete",
//     },
//     {
//       id: "avatar",
//       title: "Avatar",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/extra-components/avatar",
//     },
//     {
//       id: "chips",
//       title: "Chips",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/extra-components/chips",
//     },
//     {
//       id: "divider",
//       title: "Divider",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/extra-components/divider",
//     },
//   ],
// },
// {
//   type: "groupHeader",
//   groupTitle: "FORMS & TABLES",
// },
// {
//   id: "formElements",
//   title: "Form Elements",
//   type: "collapse",
//   icon: <Icon.Copy size={20} />,
//   children: [
//     {
//       id: "select",
//       title: "Select",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/select",
//     },
//     {
//       id: "switch",
//       title: "Switch",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/switch",
//     },
//     {
//       id: "checkbox",
//       title: "Checkbox",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/checkbox",
//     },
//     {
//       id: "radio",
//       title: "Radio",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/radio",
//     },
//     {
//       id: "input",
//       title: "Input",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/input",
//     },
//     {
//       id: "inputGroup",
//       title: "Input Group",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/input-group",
//     },
//     {
//       id: "numberInput",
//       title: "Number Input",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/number-input",
//     },
//     {
//       id: "textarea",
//       title: "Textarea",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/textarea",
//     },
//     {
//       id: "date_&_timePicker",
//       title: "Date & Time Picker",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/pickers",
//     },
//     {
//       id: "inputMask",
//       title: "Input Mask",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/forms/elements/input-mask",
//     },
//   ],
// },
// {
//   id: "formLayouts",
//   title: "Form Layouts",
//   type: "item",
//   icon: <Icon.Box size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/forms/layout/form-layout",
// },
// {
//   id: "wizard",
//   title: "Form Wizard",
//   type: "item",
//   icon: <Icon.MoreHorizontal size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/forms/wizard",
// },
// {
//   id: "formik",
//   title: "Formik",
//   type: "item",
//   icon: <Icon.CheckCircle size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/forms/formik",
// },
// {
//   type: "groupHeader",
//   groupTitle: "PAGES",
// },
// {
//   id: "profile",
//   title: "Profile",
//   type: "item",
//   icon: <Icon.User size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/pages/profile",
//   collapsed: true,
// },
// {
//   id: "accountSettings",
//   title: "Account Settings",
//   type: "item",
//   icon: <Icon.Settings size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/pages/account-settings",
// },
// {
//   id: "faq",
//   title: "FAQ",
//   type: "item",
//   icon: <Icon.HelpCircle size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/pages/faq",
// },

// {
//   id: "knowledgeBase",
//   title: "Knowledge Base",
//   type: "item",
//   icon: <Icon.Info size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/pages/knowledge-base",
//   parentOf: [
//     "/pages/knowledge-base/category/questions",
//     "/pages/knowledge-base/category",
//   ],
// },
// {
//   id: "search",
//   title: "Search",
//   type: "item",
//   icon: <Icon.Search size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/pages/search",
// },

// {
//   id: "invoice",
//   title: "Invoice",
//   type: "item",
//   icon: <Icon.File size={20} />,
//   permissions: ["admin", "editor"],
//   navLink: "/pages/invoice",
// },

// {
//   id: "authentication",
//   title: "Authentication",
//   type: "collapse",
//   icon: <Icon.Unlock size={20} />,
//   children: [
//     {
//       id: "login",
//       title: "Login",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/pages/login",
//       newTab: true,
//     },
//     {
//       id: "register",
//       title: "Register",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/pages/register",
//       newTab: true,
//     },
//     {
//       id: "forgotPassword",
//       title: "Forgot Password",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/pages/forgot-password",
//       newTab: true,
//     },
//     {
//       id: "resetPassword",
//       title: "Reset Password",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/pages/reset-password",
//       newTab: true,
//     },
//     {
//       id: "lockScreen",
//       title: "Lock Screen",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/pages/lock-screen",
//       newTab: true,
//     },
//   ],
// },
// {
//   id: "miscellaneous",
//   title: "Miscellaneous",
//   type: "collapse",
//   icon: <Icon.FileText size={20} />,
//   children: [
//     {
//       id: "comingSoon",
//       title: "Coming Soon",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/misc/coming-soon",

//       newTab: true,
//     },
//     {
//       id: "error",
//       title: "Error",
//       type: "collapse",
//       icon: <Icon.Circle size={12} />,
//       children: [
//         {
//           id: "404",
//           title: "404",
//           type: "item",

//           icon: <Icon.Circle size={12} />,
//           permissions: ["admin", "editor"],
//           navLink: "/misc/error/404",

//           newTab: true,
//         },
//         {
//           id: "500",
//           title: "500",
//           type: "item",

//           icon: <Icon.Circle size={12} />,
//           permissions: ["admin", "editor"],
//           navLink: "/misc/error/500",

//           newTab: true,
//         },
//       ],
//     },
//     {
//       id: "notAuthorized",
//       title: "Not Authorized",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/misc/not-authorized",

//       newTab: true,
//     },
//     {
//       id: "maintenance",
//       title: "Maintenance",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/misc/maintenance",

//       newTab: true,
//     },
//   ],
// },
// {
//   type: "groupHeader",
//   groupTitle: "CHARTS & MAPS",
// },
// {
//   id: "charts",
//   title: "Charts",
//   type: "collapse",
//   badge: "success",
//   badgeText: "3",
//   icon: <Icon.PieChart size={20} />,
//   children: [
//     {
//       id: "apex",
//       title: "Apex",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/charts/apex",
//     },
//     {
//       id: "chartJs",
//       title: "ChartJS",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/charts/chartjs",
//     },
//     {
//       id: "recharts",
//       title: "Recharts",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/charts/recharts",
//     },
//   ],
// },
// {
//   id: "leafletMaps",
//   title: "Leaflet Maps",
//   icon: <Icon.Map size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/maps/leaflet",
// },
// {
//   type: "groupHeader",
//   groupTitle: "EXTENSIONS",
// },
// {
//   id: "sweetAlert",
//   title: "Sweet Alerts",
//   icon: <Icon.AlertCircle size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/sweet-alert",
// },
// {
//   id: "toastr",
//   title: "Toastr",
//   icon: <Icon.Zap size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/toastr",
// },
// {
//   id: "rcSlider",
//   title: "Rc Slider",
//   icon: <Icon.Sliders size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/slider",
// },
// {
//   id: "fileUploader",
//   title: "File Uploader",
//   icon: <Icon.UploadCloud size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/file-uploader",
// },
// {
//   id: "wysiwygEditor",
//   title: "Wysiwyg Editor",
//   icon: <Icon.Edit size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/wysiwyg-editor",
// },
// {
//   id: "drag_&_drop",
//   title: "Drag & Drop",
//   icon: <Icon.Droplet size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/drag-and-drop",
// },
// {
//   id: "tour",
//   title: "Tour",
//   icon: <Icon.Info size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/tour",
// },
// {
//   id: "clipBoard",
//   title: "Clipboard",
//   icon: <Icon.Copy size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/clipboard",
// },
// {
//   id: "contentMenu",
//   title: "Context Menu",
//   icon: <Icon.Menu size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/context-menu",
// },
// {
//   id: "swiper",
//   title: "Swiper",
//   icon: <Icon.Smartphone size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/swiper",
// },

// {
//   id: "i18n",
//   title: "I18n",
//   icon: <Icon.Globe size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/i18n",
// },
// {
//   id: "treeView",
//   title: "Tree",
//   icon: <Icon.GitPullRequest size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/tree",
// },
// {
//   id: "extPagination",
//   title: "Pagination",
//   icon: <Icon.MoreHorizontal size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/pagination",
// },
// {
//   id: "extImport",
//   title: "Import",
//   icon: <Icon.DownloadCloud size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/import",
// },
// {
//   id: "extExport",
//   title: "Export",
//   icon: <Icon.UploadCloud size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "/extensions/export",
// },
// {
//   id: "extExportSelected",
//   title: "Export Selected",
//   icon: <Icon.CheckSquare size={20} />,
//   type: "item",
//   navLink: "/extensions/export-selected",
//   permissions: ["admin", "editor"],
// },
// {
//   type: "groupHeader",
//   groupTitle: "OTHERS",
// },
// {
//   id: "menuLevels",
//   title: "Menu Levels",
//   icon: <Icon.Menu size={20} />,
//   type: "collapse",
//   children: [
//     {
//       id: "secondLevel",
//       title: "Second Level",
//       icon: <Icon.Circle size={12} />,
//       type: "item",
//       permissions: ["admin", "editor"],
//       navlink: "",
//     },
//     {
//       id: "secondLevel1",
//       title: "Second Level",
//       icon: <Icon.Circle size={12} />,
//       type: "collapse",

//       children: [
//         {
//           id: "ThirdLevel",
//           title: "Third Level",
//           icon: <Icon.Circle size={12} />,
//           type: "item",
//           permissions: ["admin", "editor"],
//           navLink: "",
//         },
//         {
//           id: "ThirdLevel1",
//           title: "Third Level",
//           icon: <Icon.Circle size={12} />,
//           type: "item",
//           permissions: ["admin", "editor"],
//           navLink: "",
//         },
//       ],
//     },
//   ],
// },
// {
//   id: "disabledMenu",
//   title: "Disabled Menu",
//   icon: <Icon.EyeOff size={20} />,
//   type: "item",
//   permissions: ["admin", "editor"],
//   navLink: "#",
//   disabled: true,
// },
// {
//   type: "groupHeader",
//   groupTitle: "SUPPORT",
// },
// {
//   id: "documentation",
//   title: "Documentation",
//   icon: <Icon.Folder size={20} />,
//   type: "external-link",
//   permissions: ["admin", "editor"],
//   navLink:
//     "https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/documentation",
// },
// {
//   id: "raiseSupport",
//   title: "Raise Support",
//   icon: <Icon.LifeBuoy size={20} />,
//   type: "external-link",
//   newTab: true,
//   permissions: ["admin", "editor"],
//   navLink: "https://pixinvent.ticksy.com/",
// },

// export default navigationConfig;
// {
//   id: "eCommerce",
//   title: "Ecommerce",
//   type: "collapse",
//   icon: <Icon.ShoppingCart size={20} />,
//   children: [
//     {
//       id: "shop",
//       title: "Shop",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ecommerce/shop",
//     },
//     {
//       id: "detail",
//       title: "Product Detail",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ecommerce/product-detail",
//     },
//     {
//       id: "wishList",
//       title: "Wish List",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ecommerce/wishlist",
//     },
//     {
//       id: "checkout",
//       title: "Checkout",
//       type: "item",
//       icon: <Icon.Circle size={12} />,
//       permissions: ["admin", "editor"],
//       navLink: "/ecommerce/checkout",
//     },
//   ],
// },
